//! Reads tools/schema.json and emits a Rust file or a TypeScript file
//! declaring the canonical schema as constants.

use std::{fs, io::Write, path::PathBuf};

use anyhow::{Context, Result};
use clap::Parser;
use serde::Deserialize;

#[derive(Parser)]
#[command(about = "Code-generate schema constants from tools/schema.json")]
struct Cli {
    /// Output language.
    #[arg(long, value_parser = ["rust", "ts"])]
    lang: String,
    /// Output path; if omitted, writes to stdout.
    #[arg(long)]
    out: Option<PathBuf>,
    /// Input schema path.
    #[arg(long, default_value = "tools/schema.json")]
    r#in: PathBuf,
}

#[derive(Deserialize)]
struct Schema {
    version: String,
    #[allow(dead_code)]
    #[serde(rename = "topNodeKind")]
    top_node_kind: String,
    nodes: Vec<Node>,
    marks: Vec<Mark>,
}

#[derive(Deserialize)]
struct Node {
    kind: String,
    #[serde(default)]
    #[allow(dead_code)]
    group: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    content: Option<String>,
    #[serde(default, rename = "isBlock")]
    #[allow(dead_code)]
    is_block: bool,
    #[serde(default, rename = "isInline")]
    #[allow(dead_code)]
    is_inline: bool,
    #[serde(default, rename = "isCode")]
    #[allow(dead_code)]
    is_code: bool,
    #[serde(default, rename = "isTopNode")]
    #[allow(dead_code)]
    is_top_node: bool,
    #[serde(default)]
    #[allow(dead_code)]
    attrs: Vec<AttrSpec>,
    #[serde(default)]
    #[allow(dead_code)]
    markdown: Option<NodeMarkdown>,
}

#[derive(Deserialize)]
struct NodeMarkdown {
    #[allow(dead_code)]
    kind: String,
}

#[derive(Deserialize)]
struct Mark {
    kind: String,
    #[serde(default)]
    #[allow(dead_code)]
    attrs: Vec<AttrSpec>,
    #[serde(default)]
    markdown: Option<MarkMarkdown>,
}

#[derive(Deserialize, Default, Clone)]
#[serde(default)]
struct MarkMarkdown {
    delimiter: String,
    #[serde(rename = "openTag")]
    open_tag: String,
    #[serde(rename = "closeTag")]
    close_tag: String,
    #[serde(rename = "noNesting")]
    no_nesting: bool,
    #[allow(dead_code)]
    kind: String,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct AttrSpec {
    name: String,
    r#type: Option<String>,
    default: Option<serde_json::Value>,
    min: Option<i64>,
    max: Option<i64>,
    #[serde(default)]
    optional: bool,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let raw = fs::read_to_string(&cli.r#in)
        .with_context(|| format!("read schema {}", cli.r#in.display()))?;
    let schema: Schema = serde_json::from_str(&raw).context("decode schema")?;

    let output = match cli.lang.as_str() {
        "rust" => emit_rust(&schema),
        "ts" => emit_ts(&schema),
        other => anyhow::bail!("unknown lang: {other}"),
    };

    match cli.out {
        Some(path) => {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).ok();
            }
            fs::write(&path, output).with_context(|| format!("write {}", path.display()))?;
        }
        None => {
            std::io::stdout().write_all(output.as_bytes())?;
        }
    }
    Ok(())
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn emit_rust(s: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// Code generated by tools/schemagen. DO NOT EDIT.\n\n");
    out.push_str("#![allow(dead_code)]\n\n");
    out.push_str(&format!(
        "pub const SCHEMA_VERSION: &str = \"{}\";\n\n",
        s.version
    ));

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum NodeKind {\n");
    for n in &s.nodes {
        out.push_str(&format!("    {},\n", pascal_case(&n.kind)));
    }
    out.push_str("}\n\n");
    out.push_str(
        "impl NodeKind {\n    pub fn as_str(self) -> &'static str {\n        match self {\n",
    );
    for n in &s.nodes {
        out.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            pascal_case(&n.kind),
            n.kind
        ));
    }
    out.push_str("        }\n    }\n}\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum MarkKind {\n");
    for m in &s.marks {
        out.push_str(&format!("    {},\n", pascal_case(&m.kind)));
    }
    out.push_str("}\n\n");
    out.push_str(
        "impl MarkKind {\n    pub fn as_str(self) -> &'static str {\n        match self {\n",
    );
    for m in &s.marks {
        out.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            pascal_case(&m.kind),
            m.kind
        ));
    }
    out.push_str("        }\n    }\n}\n\n");

    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("pub struct MarkMarkdownMeta {\n    pub delimiter: &'static str,\n    pub open_tag: &'static str,\n    pub close_tag: &'static str,\n    pub no_nesting: bool,\n}\n\n");

    out.push_str(
        "pub fn mark_serialization(kind: MarkKind) -> MarkMarkdownMeta {\n    match kind {\n",
    );
    for m in &s.marks {
        let md = m.markdown.clone().unwrap_or_default();
        out.push_str(&format!(
            "        MarkKind::{} => MarkMarkdownMeta {{ delimiter: \"{}\", open_tag: \"{}\", close_tag: \"{}\", no_nesting: {} }},\n",
            pascal_case(&m.kind),
            md.delimiter,
            md.open_tag,
            md.close_tag,
            md.no_nesting
        ));
    }
    out.push_str("    }\n}\n");

    out
}

fn emit_ts(_s: &Schema) -> String {
    // Stub — Task 4 implements this. Returning a plain error message
    // keeps the binary's error contract intact (no panics from a CLI flag).
    String::from("// ts emitter not implemented yet (Task 4)\n")
}
